/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kz.diploma.integration.yandex.api;

import kz.diploma.integration.yandex.model.FilterDataResponse;
import kz.diploma.integration.yandex.model.YandexRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Validated
@Api(value = "YandexController", description = "the YandexController API")
public interface YandexControllerApi {

    @ApiOperation(value = "", nickname = "getFilterData", notes = "", response = FilterDataResponse.class, tags={ "yandex-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FilterDataResponse.class) })
    @RequestMapping(value = "/yandex/integration/filter-data",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<FilterDataResponse> getFilterData();


    @ApiOperation(value = "", nickname = "getSpeech", notes = "", response = String.class, tags={ "yandex-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class) })
    @RequestMapping(value = "/yandex/integration",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<String> getSpeech(@ApiParam(value = "" ,required=true )  @Valid @RequestBody YandexRequest yandexRequest);

}
